#!/bin/bash

echo "🔍 Checking Nginx configuration for timeout issues..."
echo ""

# Find nginx config files
NGINX_CONF="/etc/nginx/nginx.conf"
SITES_AVAILABLE="/etc/nginx/sites-available/default"
SITES_ENABLED="/etc/nginx/sites-enabled/default"

echo "📋 Current configurations:"
echo ""

if [ -f "$SITES_ENABLED" ]; then
    echo "=== /etc/nginx/sites-enabled/default ==="
    cat "$SITES_ENABLED"
    echo ""
elif [ -f "$SITES_AVAILABLE" ]; then
    echo "=== /etc/nginx/sites-available/default ==="
    cat "$SITES_AVAILABLE"
    echo ""
fi

echo ""
echo "════════════════════════════════════════════════════"
echo "🔧 NGINX TIMEOUT FIX NEEDED"
echo "════════════════════════════════════════════════════"
echo ""
echo "Your nginx is likely timing out before the backend completes."
echo "You need to add these timeout directives to your nginx config:"
echo ""
echo "Edit the file: /etc/nginx/sites-available/default"
echo ""
echo "Add these lines in the 'location /api/' block (or server block):"
echo ""
echo "    # Increase timeouts for long-running device operations"
echo "    proxy_read_timeout 900s;"
echo "    proxy_connect_timeout 900s;"
echo "    proxy_send_timeout 900s;"
echo "    client_body_timeout 900s;"
echo "    client_header_timeout 900s;"
echo "    send_timeout 900s;"
echo ""
echo "Example configuration:"
echo ""
echo "    location /api/ {"
echo "        proxy_pass http://localhost:5000;"
echo "        proxy_http_version 1.1;"
echo "        proxy_set_header Upgrade \$http_upgrade;"
echo "        proxy_set_header Connection 'upgrade';"
echo "        proxy_set_header Host \$host;"
echo "        proxy_cache_bypass \$http_upgrade;"
echo ""
echo "        # Extended timeouts for device operations"
echo "        proxy_read_timeout 900s;"
echo "        proxy_connect_timeout 900s;"
echo "        proxy_send_timeout 900s;"
echo "    }"
echo ""
echo "After editing, run:"
echo "    sudo nginx -t           # Test configuration"
echo "    sudo systemctl reload nginx    # Apply changes"
echo ""
echo "════════════════════════════════════════════════════"
